---
title: "COSMOS-tutorial"
author: "A. Dugourd and A. Gabor"
date: "11/10/2020"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
  ---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(cosmos)
```

## tutorial section: signaling to metabolism

```{r}

meta_network <- cosmos:::meta_network_test
signaling_data <- cosmos:::signaling_input_test
expression_data <- cosmos:::expression_data_test
metabolic_data <- cosmos:::metabolic_data_test


res <- preprocess_COSMOS_signaling_to_metabolism(signaling_data = signaling_data,
                                                 meta_network = meta_network,
                                                 metabolic_data = metabolic_data,
                                                 diff_expression_data = expression_data,
                                                 remove_unexpressed_nodes = TRUE,
                                                 filter_tf_gene_interaction_by_optimization = FALSE)

CARNIVAL_options = cosmos::default_CARNIVAL_options()
CARNIVAL_options$solverPath = "/Applications/CPLEX_Studio128/cplex/bin/x86-64_osx/cplex"

res_network = run_COSMOS_signaling_to_metabolism(data = res,
                                                 CARNIVAL_options = CARNIVAL_options,
                                                 test_run=TRUE)
```


## tutorial section: metabolism to signaling 
```{r}
meta_network <- cosmos:::meta_network_test
signaling_data <- cosmos:::signaling_input_test
expression_data <- cosmos:::expression_data_test
metabolic_data <- cosmos:::metabolic_data_test


res <- preprocess_COSMOS_metabolism_to_signaling(signaling_data = signaling_data,
                                                 meta_network = meta_network,
                                                 metabolic_data = metabolic_data,
                                                 diff_expression_data = expression_data,
                                                 filter_tf_gene_interaction_by_optimization = FALSE)

CARNIVAL_options = cosmos::default_CARNIVAL_options()
CARNIVAL_options$solverPath = "/Applications/CPLEX_Studio128/cplex/bin/x86-64_osx/cplex"

res_network = run_COSMOS_metabolism_to_signaling(data = res,
                                                 CARNIVAL_options = CARNIVAL_options,
                                                 test_run=TRUE)
```


